### PR TITLE
defualt?????????

### PR DESCRIPTION
**Pull request by TKADoggo**
is this actually a misspelling or its because you guys are really ass at english grammar smh

### CODE REVIEW

**Comment by TKADoggo** [comment]
so i was borrowing the icon bop code for my fnf mod (because im ass at coding), and when i recheck your codes, i literally saw "defualt" lmao
is this a misspell or actually the function name

**Comment by KlavierGayming** [comment]
Luckydog is russian do you expect him to not suck at this

**Comment by TKADoggo** [comment]
> Luckydog is russian do you expect him to not suck at this

didnt know hes russian

**Comment by KlavierGayming** [comment]
kay

**Comment by zacksgamerz** [comment]
Lol sorry

**Pull request merged**
